baseurl: "/"
title: My Blog
theme: ghostwriter

author:
  name: Shaham Noorani
  profile: "Shaham Noorani"

params:
  mainSections:
    - post
  intro: true
  headline: Shaham Noorani's blog
  description: A collection of advice and my life experiences
  github: "https://github.com/shaham-noorani"
  linkedin: "https://linkedin.com/in/shahamn/"
  email: shahamnoorani@gmail.com
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  readingTime: true
  readingTimeText: "Estimated reading time:"

permalinks:
  post: "/:filename/"