baseurl: "/"
title: EarlyDays
paginate: 8
theme: hugo-PaperMod

author:
  name: Shaham Noorani
  profile: "Shaham Noorani"

languages:
  en:
    languageName: "English"
    weight: 1

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Shaham Noorani's Blog"
  author: Shaham Noorani
  ShowReadingTime: true
  defaultTheme: dark
  ShowShareButtons: true
  displayFullLangName: true

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      Welcome to my blog where I share my hot-takes on **productivity**, the world of **software 
      engineering**, and whatever else **I feel like talking about**, as well as events from my **day-to-day**.
      Also, feel free to email me with any feedback or questions using the mail icon below!

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/shahamn/"
    - name: github
      url: "https://github.com/shahamn"
    - name: drive
      url: "https://drive.google.com/file/d/1HdajkjNnWgyAM9TSPyZzfV1rot6PwwQl/view?usp=sharing"
    - name: email
      url: "mailto:shahamnoorani@gmail.com"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
